/* music */
export const REQUEST_ALL_MUSIC_ASSETS = 'REQUEST_ALL_MUSIC_ASSETS';
export const RECIEVE_ALL_MUSIC_ASSETS = 'RECIEVE_ALL_MUSIC_ASSETS';
export const FETCH_ALL_MUSIC_ASSETS = 'FETCH_ALL_MUSIC_ASSETS';

/* blog posts */
export const REQUEST_ALL_BLOG_POSTS = 'REQUEST_ALL_BLOG_POSTS';
export const RECIEVE_ALL_BLOG_POSTS = 'RECIEVE_ALL_BLOG_POSTS';
export const FETCH_ALL_BLOG_POSTS = 'FETCH_ALL_BLOG_POSTS';